@AIRoundTableSecretSharingAPI_HostAddress = http://localhost:5149
@apiKey = pA-secret-key-2026-abc123

### Get current epoch
GET {{AIRoundTableSecretSharingAPI_HostAddress}}/api/registry/epoch
Accept: application/json
X-API-Key: {{apiKey}}

### Get active producers
GET {{AIRoundTableSecretSharingAPI_HostAddress}}/api/registry/producers
Accept: application/json
X-API-Key: {{apiKey}}

### Get all public keys
GET {{AIRoundTableSecretSharingAPI_HostAddress}}/api/keyexchange/keys
Accept: application/json
X-API-Key: {{apiKey}}

### Get key exchange status
GET {{AIRoundTableSecretSharingAPI_HostAddress}}/api/keyexchange/status
Accept: application/json
X-API-Key: {{apiKey}}

### Submit a metric
POST {{AIRoundTableSecretSharingAPI_HostAddress}}/api/metrics/submit
Content-Type: application/json
X-API-Key: {{apiKey}}

{
  "producerId": "partnerA",
  "country": "USA",
  "month": "2026-01-01",
  "value": 1230000,
  "epochId": 1,
  "signature": "demo"
}

### Get aggregate
GET {{AIRoundTableSecretSharingAPI_HostAddress}}/api/metrics/aggregate?country=USA&month=2026-01-01
Accept: application/json
X-API-Key: {{apiKey}}

###
